#So excited to write my first pipeline

trigger:  
-master

pool:
  vmImage: windows-latest

stages:
- stage: Build  
  displayName: Total Serve Client Application

  Steps: 
   - script: npm install
     displayName: Restore Packages

   - script: npm run build
     displayName: Build Application







